-- Schema: gu
-- ConnectMarket application database namespace.
-- This script is tracked for manual execution; it is not run automatically by Spring Boot.

BEGIN;

CREATE SCHEMA IF NOT EXISTS gu AUTHORIZATION sorelle;

-- Table: Client
CREATE TABLE IF NOT EXISTS gu.client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'ACTIF',
    "dateCreation" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_client_email UNIQUE (email),
    CONSTRAINT uq_client_login UNIQUE (login)
);

-- Table: Administrateur
CREATE TABLE IF NOT EXISTS gu.administrateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'ACTIF',
    "dateCreation" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_administrateur_email UNIQUE (email),
    CONSTRAINT uq_administrateur_login UNIQUE (login)
);

-- Table: Vendeur
CREATE TABLE IF NOT EXISTS gu.vendeur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'ACTIF',
    "dateCreation" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vendeur_email UNIQUE (email),
    CONSTRAINT uq_vendeur_login UNIQUE (login)
);

-- The password column must contain a password hash, never a plaintext password.

COMMIT;
