-- Schema: gu
-- ConnectMarket application database namespace.
-- This script is tracked for manual execution; it is not run automatically by Spring Boot.

BEGIN;

CREATE SCHEMA IF NOT EXISTS gu AUTHORIZATION sorelle;

-- Table: Type utilisateur
-- The lookup values determine whether an utilisateur is a client, vendeur, or administrateur.
CREATE TABLE IF NOT EXISTS gu.type_utilisateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    tu_name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_type_utilisateur_code UNIQUE (code),
    CONSTRAINT uq_type_utilisateur_name UNIQUE (tu_name)
);

INSERT INTO gu.type_utilisateur (code, tu_name)
VALUES
    ('CLIENT', 'Client'),
    ('VENDEUR', 'Vendeur'),
    ('ADMINISTRATEUR', 'Administrateur')
ON CONFLICT (code) DO UPDATE
SET tu_name = EXCLUDED.tu_name;

-- Table: Utilisateurs
CREATE TABLE IF NOT EXISTS gu.utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_utilisateur_id BIGINT NOT NULL REFERENCES gu.type_utilisateur(id),
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'ACTIF',
    "dateCreation" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_utilisateurs_email UNIQUE (email),
    CONSTRAINT uq_utilisateurs_login UNIQUE (login)
);

CREATE INDEX IF NOT EXISTS idx_utilisateurs_type_utilisateur
    ON gu.utilisateurs (type_utilisateur_id);

-- Table: BASIC_RIGHTS
CREATE TABLE IF NOT EXISTS gu.basic_rights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    br_name VARCHAR(150) NOT NULL,
    CONSTRAINT uq_basic_rights_code UNIQUE (code)
);

-- Table: Password history
-- Each password row belongs to one utilisateur and preserves the complete password history.
CREATE TABLE IF NOT EXISTS gu.password_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL REFERENCES gu.utilisateurs(id),
    "password" VARCHAR(255) NOT NULL,
    "current" BOOLEAN NOT NULL DEFAULT TRUE,
    date_insertion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_changement TIMESTAMPTZ,
    CONSTRAINT chk_password_history_current_dates CHECK (
        ("current" AND date_changement IS NULL)
        OR (NOT "current" AND date_changement IS NOT NULL)
    )
);

-- A user may have one current password only; prior password rows remain as history.
CREATE UNIQUE INDEX IF NOT EXISTS uq_password_history_current_utilisateur
    ON gu.password_history (utilisateur_id)
    WHERE "current";

CREATE INDEX IF NOT EXISTS idx_password_history_utilisateur_date
    ON gu.password_history (utilisateur_id, date_insertion DESC);

-- Inserting or reactivating a current password archives the prior current password for that user.
-- Password values and their utilisateur association are immutable: insert a new row instead of overwriting history.
CREATE OR REPLACE FUNCTION gu.manage_password_history()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF NEW."password" IS DISTINCT FROM OLD."password" THEN
            RAISE EXCEPTION 'Password history is immutable. Insert a new password_history row instead.';
        END IF;

        IF NEW.utilisateur_id IS DISTINCT FROM OLD.utilisateur_id THEN
            RAISE EXCEPTION 'A password history row cannot be moved to another utilisateur.';
        END IF;

        IF NOT OLD."current" AND NEW."current" THEN
            UPDATE gu.password_history
            SET "current" = FALSE,
                date_changement = CURRENT_TIMESTAMP
            WHERE "current"
              AND id <> NEW.id
              AND utilisateur_id = NEW.utilisateur_id;

            NEW.date_changement := NULL;
        ELSIF OLD."current" AND NOT NEW."current" THEN
            NEW.date_changement := COALESCE(NEW.date_changement, CURRENT_TIMESTAMP);
        END IF;
    ELSIF TG_OP = 'INSERT' AND NEW."current" THEN
        UPDATE gu.password_history
        SET "current" = FALSE,
            date_changement = CURRENT_TIMESTAMP
        WHERE "current"
          AND utilisateur_id = NEW.utilisateur_id;

        NEW.date_changement := NULL;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_password_history_manage_current ON gu.password_history;

CREATE TRIGGER trg_password_history_manage_current
BEFORE INSERT OR UPDATE OF "password", "current", utilisateur_id ON gu.password_history
FOR EACH ROW
EXECUTE FUNCTION gu.manage_password_history();

COMMIT;
